services:
  web:
    build:
      context: .
      dockerfile: docker/local/django/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    image: mysql:8
    restart: always
    ports:
      - "3960:3306"
    env_file:
        - .env
    volumes:
      - ./docker/local/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin --user=$${MYSQL_USER} --password=$${MYSQL_PASSWORD} --host=localhost ping"]
      interval: 5s
      retries: 5
      timeout: 5s