services:
  web:
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_NAME=game_db
      - DB_USER=game_user
      - DB_PASSWORD=game_pass
      - DB_HOST=db
      - DB_PORT=3306

  db:
    image: mysql:8
    restart: always
    ports:
      - "3960:3306"
    environment:
      MYSQL_DATABASE: game_db
      MYSQL_USER: game_user
      MYSQL_PASSWORD: game_pass
      MYSQL_ROOT_PASSWORD: secure_root_password
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      timeout: 5s